import { launchInterProScan } from './launchInterProScan'

test('interpro', async () => {
  const res = await launchInterProScan({
    algorithm: 'interproscan',
    onProgress: arg => {
      console.log('here', arg)
    },
    seq: 'RPTVARQVFQPAYAPAVLSKFDPRTEADVDEVAFSKHTSNQESLPPVFRMVAKEYANRVFTLLGKDNGRLTVKQALEGLEGMDPMDRNTSPGLPYTALGMRRTDVVDWESATLIPFAAERLRKMNEGDFSEVVYQTFLKDELRPIEKVQAAKTRIVDVPPFEHCILGRQLLGKFASKFQTQPGLELGSAIGCDPDVHWTAFGVAMQGFERVYDVDYSNFDSTHSVAMFRLLAEEFFTPENGFDPLTREYLESLAISTHAFEEKRFLITGGLPSGCAATSMLNTIMNNIIIRAGLYLTYKNFEFDDVKVLSYGDDLLVATNYQLDFDKVRASLAKTGYKITPANTTSTFPLNSTLEDVVFLKRKFKKEGPLYRPVMNREALEAMLSYYRPGTLSEKLTSITMLAVHSGKQEYDRLFAPFREVGV',
  })
  console.log({ res })
}, 1_000_000)
